export const surpriseMePrompts = [
    'A castle made entirely of candy, inhabited by friendly dragons and unicorns',
    'A group of penguins having a dance party in an igloo disco, surrounded by colorful lights and snowflakes',
    'A magical forest where trees are made of candy canes and the ground is covered in rainbow-colored leaves',
    'A futuristic cityscape with flying cars zooming past skyscrapers adorned with neon lights and holographic billboards',
    'A cozy cottage nestled in the clouds, with fluffy sheep grazing peacefully on cotton candy fields',
    'A steampunk-inspired underwater city inhabited by mermaids and mechanical sea creatures',
    'A whimsical tea party in an enchanted garden, attended by animals wearing top hats and monocles',
    'A time-traveling adventure aboard a steam-powered pirate ship, sailing through a sky filled with shooting stars',
    'A carnival in space, complete with gravity-defying rides and cotton candy asteroids',
    'A secret underground bunker where robots and aliens collaborate on inventing the next breakthrough technology',
    'An ancient temple hidden deep in the jungle, guarded by mystical creatures and overgrown with bioluminescent plants',
    'A post-apocalyptic world where nature has reclaimed the ruins of human civilization, with towering trees growing through abandoned buildings',
    'A whimsical underwater kingdom ruled by a benevolent octopus queen, surrounded by colorful coral reefs and playful sea creatures',
    'A fantasy library with books that come to life, filled with magical creatures and endless adventures',
    'A celestial garden floating in space, with blooming flowers made of stardust and constellations illuminating the sky',
    'A magical train journey through a land of dreams, with whimsical creatures and fantastical landscapes passing by the windows',
    'A futuristic metropolis where robots and humans coexist harmoniously, with towering skyscrapers and bustling street markets',
    'A hidden valley inhabited by friendly giants, with waterfalls cascading down crystal cliffs and rainbows arching overhead',
    'An enchanted ice palace nestled atop a snowy mountain, with shimmering icicles and dancing auroras lighting up the sky',
    'A mystical forest inhabited by talking animals and fairies, with ancient trees whispering secrets to those who listen',
    'A cyberpunk cityscape with neon-lit alleyways and towering holographic billboards, bustling with humans and androids alike',
    'A magical garden where plants grow in the shape of musical instruments, playing melodies as the wind blows through their leaves',
    'An intergalactic space station bustling with activity, with aliens from different planets trading goods and sharing stories',
    'A steampunk airship floating gracefully through the clouds, with adventurers aboard embarking on a journey to unknown lands',
    'A hidden oasis in the desert, with palm trees swaying in the breeze and a shimmering oasis pool reflecting the stars above',
    'A whimsical village inhabited by quirky creatures, with mushroom houses and colorful gardens dotting the landscape',
    'A futuristic laboratory where scientists conduct experiments with teleportation and time manipulation, surrounded by swirling energy fields',
    'A mythical island shrouded in mist, with ancient ruins and mysterious creatures lurking in the shadows',
    'A cosmic carnival traveling through space, with rides and attractions floating in zero gravity and aliens enjoying the festivities',
    'A magical marketplace where wizards and witches trade potions and spellbooks, with enchanted broomsticks parked outside shops',
  ];
  